name: Build and test (catkin)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'

jobs:

  clang-format:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install clang-format-10
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y -qq install clang-format-10
      - name: Run clang-format-check
        run: |
          ./.clang-format-check.sh

  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        build-type: [RelWithDebInfo, Debug]
        mc-rtc-version: [head, stable]
        footstep-planner: [ON]
        exclude:
          - build-type: Debug
            mc-rtc-version: stable
        include:
          - os: ubuntu-20.04
            build-type: RelWithDebInfo
            mc-rtc-version: head
            footstep-planner: OFF
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set ROS version
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-20.04" ]; then
            echo "ROS_DISTRO=noetic" >> $GITHUB_ENV
            echo "PYTHON_PACKAGE_PREFIX=python3" >> $GITHUB_ENV
          else
            echo "ROS_DISTRO=melodic" >> $GITHUB_ENV
            echo "PYTHON_PACKAGE_PREFIX=python" >> $GITHUB_ENV
          fi
      - name: Install ROS
        run: |
          set -e
          set -x
          sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
          wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq ros-${ROS_DISTRO}-ros-base ${PYTHON_PACKAGE_PREFIX}-catkin-tools ${PYTHON_PACKAGE_PREFIX}-rosdep ${PYTHON_PACKAGE_PREFIX}-wstool doxygen graphviz
      - name: Install mc_rtc
        run: |
          set -e
          set -x
          curl -1sLf 'https://dl.cloudsmith.io/public/mc-rtc/${{ matrix.mc-rtc-version }}/setup.deb.sh' | sudo -E bash
          sudo apt install -y -qq libmc-rtc-dev mc-rtc-utils ros-${ROS_DISTRO}-mc-rtc-plugin libeigen-qld-dev
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: catkin_ws/src/isri-aist/BaselineWalkingController
      - name: Download dependent repository codes
        run: |
          set -e
          set -x
          cd ${GITHUB_WORKSPACE}/catkin_ws
          wstool init src
          wstool update -t src isri-aist/BaselineWalkingController
          wstool merge -t src src/isri-aist/BaselineWalkingController/depends.rosinstall -y
          wstool update -t src
      - name: Rosdep install
        run: |
          set -e
          set -x
          cd ${GITHUB_WORKSPACE}/catkin_ws
          set +x
          . /opt/ros/${ROS_DISTRO}/setup.bash
          set -x
          sudo rosdep init
          rosdep update
          rosdep install -y -r --from-paths src --ignore-src
      - name: Remove BaselineFootstepPlanner
        if: matrix.footstep-planner == 'OFF'
        run: |
          set -e
          set -x
          cd ${GITHUB_WORKSPACE}/catkin_ws
          wstool remove -t src isri-aist/BaselineFootstepPlanner
          rm -rf isri-aist/BaselineFootstepPlanner
      - name: Catkin build
        run: |
          set -e
          set -x
          cd ${GITHUB_WORKSPACE}/catkin_ws
          set +x
          . /opt/ros/${ROS_DISTRO}/setup.bash
          set -x
          if [ "${{ matrix.footstep-planner }}" == "ON" ]; then
            catkin build baseline_footstep_planner --limit-status-rate 0.1 -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
            set +x
            . devel/setup.bash
            set -x
          fi
          catkin build baseline_walking_controller --limit-status-rate 0.1 -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DENABLE_QLD=ON -DINSTALL_DOCUMENTATION=ON
      - name: Run tests
        run: |
          set -e
          set -x
          cd ${GITHUB_WORKSPACE}/catkin_ws
          set +x
          . devel/setup.bash
          set -x
          catkin build baseline_walking_controller --no-deps --limit-status-rate 0.1 --catkin-make-args run_tests
          catkin_test_results --verbose --all build
      - name: Run simulation
        # Only run for one configuration
        if: matrix.os == 'ubuntu-20.04' && matrix.build-type == 'RelWithDebInfo' && matrix.mc-rtc-version == 'head' && matrix.footstep-planner == 'ON'
        # https://github.com/jrl-umi3218/lipm_walking_controller/blob/b564d655388ae6a6725c504e5c74a62192e58c7c/.github/workflows/build.yml#L64-L92
        run: |
          set -e
          set -x
          sudo apt-get install -y -qq mc-state-observation jvrc-choreonoid xvfb ffmpeg mesa-utils fluxbox xserver-xorg xserver-xorg-core xserver-xorg-video-all libwayland-egl1-mesa
          set +x
          . ${GITHUB_WORKSPACE}/catkin_ws/devel/setup.bash
          set -x
          export DISPLAY=":1"
          Xvfb ${DISPLAY} -screen 0 1920x1080x24 &
          sleep 10s
          fluxbox 2> /dev/null &
          mkdir -p ${HOME}/.config/mc_rtc/controllers
          cp ${GITHUB_WORKSPACE}/catkin_ws/src/isri-aist/BaselineWalkingController/etc/mc_rtc.yaml ${HOME}/.config/mc_rtc
          cp ${GITHUB_WORKSPACE}/catkin_ws/src/isri-aist/BaselineWalkingController/.github/workflows/config/WalkingOnPlane.yaml ${HOME}/.config/mc_rtc/controllers/BaselineWalkingController.yaml
          ffmpeg -y -f x11grab -s 1920x1080 -r 30 -i ${DISPLAY} -qscale 0 -vcodec huffyuv /tmp/video.avi > /dev/null 2>&1 < /dev/null &
          FFMPEG_PID=$!
          cd /usr/share/hrpsys/samples/JVRC1
          ./clear-omninames.sh
          choreonoid --start-simulation sim_mc.cnoid &
          CNOID_PID=$!
          sleep 50s
          kill -2 ${CNOID_PID}
          kill -2 ${FFMPEG_PID}
          sleep 1s
          kill -9 ${CNOID_PID} || true
          sleep 10s
          mkdir -p /tmp/results
          ffmpeg -nostats -i /tmp/video.avi /tmp/results/video.mp4
          LOG_PATH=`readlink -f /tmp/mc-control-BaselineWalkingController-latest.bin`
          tar czf /tmp/results/`basename ${LOG_PATH}`.tar.gz -C `dirname ${LOG_PATH}` `basename ${LOG_PATH}`
      - name: Upload simulation data
        # Only run for one configuration
        if: matrix.os == 'ubuntu-20.04' && matrix.build-type == 'RelWithDebInfo' && matrix.mc-rtc-version == 'head' && matrix.footstep-planner == 'ON'
        uses: actions/upload-artifact@v3
        with:
          name: BWC-ci-results
          path: /tmp/results
      - name: Check simulation results
        # Only run for one configuration
        if: matrix.os == 'ubuntu-20.04' && matrix.build-type == 'RelWithDebInfo' && matrix.mc-rtc-version == 'head' && matrix.footstep-planner == 'ON'
        run: |
          set -e
          set -x
          EXPECTED_BASE_POS="1.34 -0.41 0.8"
          python3 ${GITHUB_WORKSPACE}/catkin_ws/src/isri-aist/BaselineWalkingController/.github/workflows/scripts/checkSimulationResults.py `readlink -f /tmp/mc-control-BaselineWalkingController-latest.bin` --expected-base-pos ${EXPECTED_BASE_POS}
      - name: Upload documentation
        # Only run for one configuration and on master branch
        if: matrix.os == 'ubuntu-20.04' && matrix.build-type == 'RelWithDebInfo' && matrix.mc-rtc-version == 'head' && matrix.footstep-planner == 'ON' && github.repository_owner == 'isri-aist' && github.ref == 'refs/heads/master'
        run: |
          set -e
          set -x
          cd ${GITHUB_WORKSPACE}/catkin_ws/src/isri-aist/BaselineWalkingController
          git config --global user.name "Masaki Murooka"
          git config --global user.email "m-murooka@aist.go.jp"
          git remote set-url origin "https://mmurooka:${{ secrets.CI_TOKEN }}@github.com/isri-aist/BaselineWalkingController"
          git fetch --depth=1 origin gh-pages:gh-pages
          git clean -dfx
          rm -rf cmake/
          git checkout --quiet gh-pages
          rm -rf doxygen/
          cp -r ${GITHUB_WORKSPACE}/catkin_ws/build/baseline_walking_controller/doc/html/ doxygen
          git add doxygen
          git_status=`git status -s`
          if test -n "$git_status"; then
            git commit --quiet -m "Update Doxygen HTML files from commit ${{ github.sha }}"
            git push origin gh-pages
          else
            echo "Github pages documentation is already up-to-date."
          fi
